### ISSUE TITLE
Add "already sent" feature

### ISSUE THREAD

**Issue by lucaoflaif** [domcorvasce/fullstack-broadcast-bot#6]
Add a function that can detect if an article was sent previously.
The the db could be a file since we don't need much read/write speed.

**Comment by domcorvasce** [comment]
I'm wondering about introduce some features which would need DB capabilities so I think we can go for something like MongoDB.

**Comment by lucaoflaif** [comment]
Perfect! A NoSQL solution should be the best choice.
